# Generated by Django 4.1.3 on 2022-11-06 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='genre',
            field=models.CharField(choices=[('SH', 'Shonen'), ('SN', 'Seinin')], default='SH', max_length=5),
            preserve_default=False,
        ),
    ]
