# Generated by Django 4.1.3 on 2022-11-07 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_article_genre'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='description',
            field=models.TextField(default='shinobi'),
            preserve_default=False,
        ),
    ]
